#!/usr/bin/env bash

#
# powermenu - a very simple rofi powermenu
#
# Copyright (C) 2025 Johannes Kamprad
#
# SPDX-License-Identifier: GPL-3.0-or-later

# needs rofi config:
# $HOME/.config/rofi/powermenu.rasi
# set to be used in i3wm + KDE Plasma:
# logout/reboot/shutdown go through Plasma's session manager (ksmserver)
# so the session is saved and apps are closed cleanly.

ROFI_THEME="${HOME}/.config/rofi/powermenu.rasi"

# Menu entries
cancel=$'\uf05e  Cancel'
lock=$'\uf023   Lock'
logout=$'\uf007   Logout'
reboot=$'\uf01e   Reboot'
shutdown=$'\uf011   Shutdown'
suspend=$'\uf186   Suspend'
hibernate=$'\uf2dc   Hibernate'

options="$cancel\n$lock\n$logout\n$reboot\n$shutdown\n$suspend\n$hibernate"

chosen="$(echo -e "$options" | rofi -dmenu -i -p "Power Menu" \
    -theme "$ROFI_THEME")"

case $chosen in
    "$lock")
        loginctl lock-session
        ;;
    "$cancel"|"")
        exit 0
        ;;
    "$logout")
        qdbus6 org.kde.Shutdown /Shutdown org.kde.Shutdown.logout
        ;;
    "$reboot")
        qdbus6 org.kde.Shutdown /Shutdown org.kde.Shutdown.logoutAndReboot
        ;;
    "$shutdown")
        qdbus6 org.kde.Shutdown /Shutdown org.kde.Shutdown.logoutAndShutdown
        ;;
    "$suspend")
        systemctl suspend
        ;;
    "$hibernate")
        systemctl hibernate
        ;;
esac
